import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

import QueryClientProviders from "@/components/queryClientProviders";
import MainNavbar from "@/components/navbar/main-navbar";
import { MilestoneProvider } from "@/components/celebration/milestone";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <MilestoneProvider>
          <QueryClientProviders>
          <MainNavbar/>
            {children}
          </QueryClientProviders>
        </MilestoneProvider>
      </body>
    </html>
  );
}
